name: farm_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  image_picker_windows: ^0.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true