// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qNtGJ2o_0WM4yw1AxLITu2efhZCdmtY',
    appId: '1:488620623240:web:244b047c81f29685b4a63d',
    messagingSenderId: '488620623240',
    projectId: 'farm-36c66',
    authDomain: 'farm-36c66.firebaseapp.com',
    databaseURL: 'https://farm-36c66-default-rtdb.firebaseio.com',
    storageBucket: 'farm-36c66.firebasestorage.app',
    measurementId: 'G-K1GBZW35S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKv3oGPvp1luIyUyisCsbbuTqScZuuPoQ',
    appId: '1:488620623240:android:0eb158a40af33aefb4a63d',
    messagingSenderId: '488620623240',
    projectId: 'farm-36c66',
    databaseURL: 'https://farm-36c66-default-rtdb.firebaseio.com',
    storageBucket: 'farm-36c66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSeHZmKBHbAbm4X51PJgqIQ0aVQH1KMHQ',
    appId: '1:488620623240:ios:81c79573c24f7421b4a63d',
    messagingSenderId: '488620623240',
    projectId: 'farm-36c66',
    databaseURL: 'https://farm-36c66-default-rtdb.firebaseio.com',
    storageBucket: 'farm-36c66.firebasestorage.app',
    iosClientId: '488620623240-0blns1os5o8gdnt0bek7or84nfeqfsl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmProduceMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSeHZmKBHbAbm4X51PJgqIQ0aVQH1KMHQ',
    appId: '1:488620623240:ios:81c79573c24f7421b4a63d',
    messagingSenderId: '488620623240',
    projectId: 'farm-36c66',
    databaseURL: 'https://farm-36c66-default-rtdb.firebaseio.com',
    storageBucket: 'farm-36c66.firebasestorage.app',
    iosClientId: '488620623240-0blns1os5o8gdnt0bek7or84nfeqfsl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmProduceMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7qNtGJ2o_0WM4yw1AxLITu2efhZCdmtY',
    appId: '1:488620623240:web:3dde5fd979d33257b4a63d',
    messagingSenderId: '488620623240',
    projectId: 'farm-36c66',
    authDomain: 'farm-36c66.firebaseapp.com',
    databaseURL: 'https://farm-36c66-default-rtdb.firebaseio.com',
    storageBucket: 'farm-36c66.firebasestorage.app',
    measurementId: 'G-NHR2ZQZGCN',
  );
}
